language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
before_script:
  - composer self-update
  - composer install --no-interaction
  - ./console -v app:install --database-name=suitecrm --database-username=travis --install-admin-username=admin --install-admin-password=admin --install-system-name="SuiteCRM Travis Build" --install-create-database --no-interaction
script:
  - cd tests
  - ../vendor/bin/phpunit
services:
  - mysql
branches:
  only:
    - master
    - hotfix
    - develop
    - IMP-MEKIT-CRM