language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm   # ZIP Error(11): Status(0): Arhive(cache/zipTest.zip): Directory(cache)
before_script:
  - composer self-update
  - composer install --no-interaction
  - \[ -f "config_si.php" \] || cp tests/travis_config_si.php config_si.php
  - php tests/testinstall.php
script:
#  - cd tests
  - vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover=coverage.clover.unit
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover.unit
services:
  - mysql
branches:
  only:
    - master
    - hotfix
    - develop
    - scrutinizer-code-quality
notifications:
  on_success: never
  on_failure: always
