imports: ~
configuration:
  title: "MEKIT CRM SYNC DOWN CONFIG"
  global:
      log_to_console: true
  sync:
    file:
      sync_command: rsync
      sync_arguments:
        # - '--dry-run'
        - '--recursive'
        - '--compress'
        - '--quiet'
        - '--cvs-exclude'
        - '--exclude-from="config/devel/excludes.txt"'
        - '--filter="protect .idea"'
      sync_source:        '-e ssh crm.mekit.it@vhsrv3.mekit.it:/home/crm.mekit.it/httpdocs/'
      sync_destination:   '/home/jack/tmp/rsynctest'
    database:
